Editing
sirpravdi/reactions pull request #3
Opened 2018-10-20 23:49 UTC by sirpravdi

code check up with linter + created dom helper

2018-10-21 08:03 UTC, gohabereg requested changes

2018-10-21 08:03 UTC, gohabereg commented on main.js
> +        var wrap = document.querySelector(".reactions-wrapper");
var стоит избегать. Последний стандарт ES определяет let и const

2018-10-21 08:03 UTC, gohabereg commented on main.js
> +    domHelper(elName, classList) {
Сюда можно добавить назначение атрибутов (вроде type, innerText, value и тд).
И метод лучше переименовать. domHelper не даёт понимания, что делает функция. Лучше назвать createElement или make, что-то подобное

2018-10-22 12:14 UTC, gohabereg requested changes

2018-10-22 12:14 UTC, gohabereg commented on main.js
> +     * @param {object} data - object containing poll emojis, title and parent element.
Можно описать внутренности `data`:
```
@param {object} data - ...
@param {HTMLElement} data.parent - ...
@param {string[]} data.reactions - ...
@param {string} title - ...
```

2018-10-22 12:14 UTC, gohabereg commented on main.js
> +            let counter = Reactions.prototype.createElement("div", "reactions-wrapper__counter");
Все вызовы через `prototype` нужно сделать через `this`

2018-10-22 12:14 UTC, gohabereg commented on main.js
> +            let counter = Reactions.prototype.createElement("div", "reactions-wrapper__counter");
И все переменные, которые не переназначаются нужно объявлять через `const`

2018-10-22 12:14 UTC, gohabereg commented on main.js
> +            let label = Reactions.prototype.createElement("label", "reactions-wrapper__emoji", {textContent: String.fromCodePoint(item)});
Подключи еще `eslint` с нашим конфигом, чтобы весь кодстайл был единым

2018-10-22 12:14 UTC, gohabereg commented on main.js
> +        let wrap = document.querySelector(".reactions-wrapper");
Чтобы не искать каждый раз обертку, можно сохранить ее внутри класса

2018-10-22 12:14 UTC, gohabereg commented on main.js
> +        if (wrap.querySelector(".reactions-wrapper__emoji_picked")) {
Если `picked` это класс для выбранного эмодзи, то по БЭМ это модификатор — `reactions-wrapper__emoji--picked`

2018-10-22 12:14 UTC, gohabereg commented on main.js
> +new Reactions({parent: document.body, title: "What do you think?", reactions: ["0x1F601", "0x1F914", "0x1F644"]});
Удобнее, когда вместо элемента передается id или селектор, а модуль уже сам берет нужный элемент

2018-10-22 12:14 UTC, gohabereg commented on main.js
> +            localStorage.setItem("reactionIndex" + prev.dataset.reactionsCounter, parseInt(localStorage.getItem("reactionIndex" + prev.dataset.reactionsCounter)) - 1);
Длинные строки, такие не очень удобно читать. Чтобы укоротить, сохраняй одинаковые части в переменные. Например тут можно сделать `storageKey = 'reactionIndex' + prev.dataset.reactionsCounter`

2018-10-22 14:48 UTC, sirpravdi commented on main.js
> +            let label = Reactions.prototype.createElement("label", "reactions-wrapper__emoji", {textContent: String.fromCodePoint(item)});
Мне казалось, что я подключила, но, выходит, сделала как-то криво, т.к. почти весь код тут после линтера

2018-10-22 15:06 UTC, sirpravdi commented on main.js
> +        let wrap = document.querySelector(".reactions-wrapper");
Я сделала, но не понимаю почему именно так работает в этом случае input.addEventListener("click", input => this.pollClick(input.target));
Почему тут input это не input, а click?

2018-10-22 15:18 UTC, gohabereg requested changes

2018-10-22 15:18 UTC, gohabereg commented on main.js
> +     * @param {object} data - object containing poll emojis, title and parent element.
Теперь у тебя `data.parent` не элемент, а селектор. Нужно поправить описание и тип параметра

2018-10-22 15:18 UTC, gohabereg commented on main.js
> +        document.querySelector(data.parent).append(this.wrap);
Тут обязательно нужна проверка на существование элемента. Если его нет, будет runtime error

2018-10-22 15:18 UTC, gohabereg commented on main.js
> +        data.reactions.forEach((item, i, arr) => {
Внутренности `forEach` можно вынести в отдельный метод, чтобы было что-то вроде `data.reactions.forEach((item, i) => this.addReaction(item, i))`

2018-10-22 15:18 UTC, gohabereg commented on main.js
> +        if (this.wrap.querySelector(".reactions-wrapper__emoji--picked")) {
Тут можно упростить логику и уменьшить количество поисков по странице, если сохранять внутри модуля сами кнопки.

2018-10-23 09:16 UTC, gohabereg commented on .eslintrc.js
> +    "extends": "codex",
Используй плиз только наш конфиг, без перегрузки правил.
У нас отступ 2 пробела, строки и одинарных ковычках

2018-10-23 09:16 UTC, gohabereg commented on package.json
> +  "bugs": {
Чтобы использовать линтер, тебе нужно установить в зависимости наш конфиг и eslint.
Тут инструкция есть — https://github.com/codex-team/eslint-config

2018-10-23 12:35 UTC, sirpravdi commented on .eslintrc.js
> +    "extends": "codex",
Конфиг постараюсь настроить как дома буду

2018-10-23 21:25 UTC, gohabereg requested changes

2018-10-24 09:03 UTC, gohabereg requested changes

2018-10-24 09:03 UTC, gohabereg commented on main.js
> +    if (this.picked) {
Стоит уменьшить вложенность кода, тогда будет более читабельно.
Для этого нужно развернуть этот if:
```
if (!this.picked) {
    // do something if there is no picked emoji
    
    return; // важно именно закончить выполнение функции
}

// do anything else
```

2018-10-24 09:03 UTC, gohabereg commented on main.js
> +      if (this.picked != clickedEmoji) {
С этим if можно аналогично поступить

2018-10-24 09:03 UTC, gohabereg commented on main.js
> +      if (this.picked != clickedEmoji) {
Если оба if развернуть, то станет гораздо лучше

2018-10-24 09:05 UTC, sirpravdi commented on main.js
> +    const index = this.createElement('span', null, {innerText: this.getCounter(storageKey)});
Этот ключ меняется, я не могу его сохранить в перменную

2018-10-24 09:07 UTC, gohabereg commented on main.js
> +    const index = this.createElement('span', null, {innerText: this.getCounter(storageKey)});
Он меняется на 0, и только если его не было в ls до этого. Код, который я предложил сверху, учитывает это

2018-10-24 12:11 UTC, gohabereg requested changes

2018-10-24 12:11 UTC, gohabereg commented on main.js
> +    const input = this.createElement('input', null, {type: 'radio', name: 'poll'});
Думаю, input можно выпилить, ты его используешь только, чтобы клик повесить. А сам клик повесить на обертку.

2018-10-24 12:11 UTC, gohabereg commented on main.js
> +      this.picked.nextSibling.innerText = this.getCounter(pickedStorageKey);
Поиск по nextSibling лучше убрать, так как в коде не понятно, что это за элемент. Здесь как раз можно сделать `this.picked.querySelector('reactions-wrapper__counter')`. Тогда станет понятно, что за элемент ты ищешь.

2018-10-24 12:11 UTC, gohabereg commented on main.js
> +      this.picked.nextSibling.innerText = this.getCounter(pickedStorageKey);
И во всех аналогичных случаях тоже лучше убрать nextSibling.

2018-10-24 12:11 UTC, gohabereg commented on main.js
> +      clickedEmoji.nextSibling.innerText = this.getCounter(clickedStorageKey);
Тоже несколько обращений к одному и тому же ключу в ls.
Здесь можно сделать так
```
const votes = this.getCounter(clickedStorageKey) + 1;
this.setCounter(clickedStorageKey, votes);

const counter = clickedEmoji.querySelector('reactions-wrapper__counter');
counter.innerHTML = votes;
```

2018-10-24 12:11 UTC, gohabereg commented on main.js
> +      clickedEmoji.nextSibling.innerText = this.getCounter(clickedStorageKey);
Тут чуть повыше и пониже в коде такие же ситуации, там тоже нужно поменять

2018-10-24 12:11 UTC, gohabereg commented on main.js
> +  reactionClicked(clickedEmoji) {
Добавь в этом методе пустых строк между кодом. Старайся, чтобы не было больше 3 строчек подряд, нужно разделять их логически

2018-10-24 12:11 UTC, gohabereg commented on main.js
> +       * processing click on emoji
Комменты к функции должны быть над функцией. Проверь везде по файлу

2018-10-24 12:11 UTC, gohabereg commented on main.js
> +    if(!this.picked){
Теперь можно задокументировать каждый кейс.
Например тут 
```
/** If there is no previous picked reaction */
```

В следующем 
```
/** If clicked reaction is not equal to previous one */
```
 И в последнем тоже

2018-10-24 12:14 UTC, sirpravdi commented on main.js
> +    const input = this.createElement('input', null, {type: 'radio', name: 'poll'});
и label'ы переделать в просто div'ы?

2018-10-24 12:37 UTC, sirpravdi commented on main.js
> +      this.picked.nextSibling.innerText = this.getCounter(pickedStorageKey);
Но this.picked не содержит в себе span, да и reactions-wrapper__counter (это его родитель)
Я могу тут обратиться разве что через this.picked.parentElement.querySelector('span')

2018-10-24 12:48 UTC, sirpravdi commented on main.js
> +      this.picked.nextSibling.innerText = this.getCounter(pickedStorageKey);
Ну или добавить к span класс и обращаться по имени класса

2018-10-24 13:38 UTC, gohabereg approved these changes

2018-10-24 13:38 UTC, gohabereg commented on main.js
> +    emoji.addEventListener('click', click => this.reactionClicked(emoji));
Тут на самом деле можно передавать сразу i. Тогда можно вообще не записывать ничего в data-атрибуты

2018-10-24 13:44 UTC, merged

2018-10-24 13:49 UTC, sirpravdi commented
.